export const About = 'About'
export const AboutCvv = '3 or 4 digits, usually on the back of the card (up front on AMEX cards)'
export const AcceptAttachedFile = 'Accept attached file'
export const AcceptCustomOptionByCustomer = 'Accept custom option by customer'
export const Active = 'Active'
export const Add = 'Add'
export const AddApp = 'Add app'
export const AddCart = 'Add cart'
export const AddClient = 'Add client'
export const Additional = 'Additional'
export const AdditionalCost = 'Additional cost'
export const Address = 'Address'
export const Addresses = 'Addresses'
export const AddressesName = 'Recipient'
export const AddPref = 'Add to preferences'
export const AddToPrice = 'Add to price'
export const AdminSettings = 'Admin Settings'
export const Advanced = 'Advanced'
export const AffiliateCoede = 'Afiliate code'
export const AfterPayment = 'After the payment approval'
export const Alt = 'Alt tag'
export const AlterationPrice = 'Default price alteration on products with this grid for customization or variations.'
export const Another = 'Another'
export const App = 'App'
export const AppDevelopers = 'App developers'
export const ApplyDiscount = 'Apply discount'
export const AtSight = 'At sight'
export const Attachment = 'Attachment'
export const Authentication = 'Authentication'
export const Available = 'Available to buy'
export const BackToCart = 'Back to cart'
export const Bag = 'Bag'
export const Banner = 'Banner'
export const Banners = 'Banners'
export const BillingAddress = 'Billing address'
export const Birthdate = 'Birthdate'
export const Borough = 'Borough'
export const Buy = 'Buy'
export const Buyer = 'Buyer'
export const By = 'by'
export const Brand = 'Brand'
export const BrandName = 'Brand name'
export const Brazil = 'Brazil'
export const BuyWith = 'Frequently bought together'
export const CalculateShipping = 'Calculate shipping'
export const Callback = 'Callback'
export const Cancel = 'Cancel'
export const Cancelled = 'Cancelled'
export const CardNumber = 'Card number'
export const CartConfirmed = 'Cart confirmed'
export const CartDetails = 'Cart details'
export const CartItems = 'Cart items'
export const Category = 'Category'
export const CategoryBanners = 'Category banner'
export const CategoryName = 'Category name'
export const Cellphone = 'Cellphone'
export const ChangePaymentMethod = 'Change payment method'
export const ChangeShippingMethod = 'Change shipping method'
export const Channel = 'Channel'
export const Channels = 'Channels'
export const Checkout = 'Buy now'
export const CheckoutEnabled = 'Checkout enabled'
export const CheckoutDone = 'Checkout done'
export const City = 'City'
export const Close = 'Close'
export const Code = 'Code'
export const CodeCopied = 'Code copied'
export const Collection = 'Collection'
export const Collections = 'Collections'
export const CollectionBanners = 'Collection banner'
export const CollectionItems = 'Collection items'
export const CollectionName = 'Collection name'
export const Color = 'Color'
export const Colors = 'Colors'
export const Community = 'Community'
export const CompanyRegistration = 'Company registration'
export const CompareProducts = 'Compare with similar items'
export const Complement = 'Complement'
export const ComplementInformation = 'Complement Information'
export const ConfirmPurchase = 'Confirm purchase'
export const ContactPhone = 'Contact phone'
export const ContactUs = 'If you have any questions, please contact us.'
export const Content = 'Content'
export const Continue = 'Continue'
export const ContinueShopping = 'Continue shopping'
export const Control = 'Control'
export const CopyCode = 'Copy code'
export const CopyErrorMsg = 'Error copying to clipboard, please copy manually'
export const CorporateName = 'Corporate name'
export const CountryCode = 'Country code'
export const CreateTransaction = 'Create transaction'
export const Creation = 'Creation'
export const Credit = 'Credit'
export const CreditCard = 'Credit card'
export const CreditCardBin = 'Credit card issuer identification'
export const CreditCardCompany = 'Credit card issuer'
export const CreditCardHolderName = 'Full name on credit card'
export const CreditCardLastDigits = 'Last digits from credit card'
export const CurrencyId = 'Currency Identifier'
export const CurrencySymbol = 'Currency symbol'
export const Custom = 'Customize'
export const CustomValue = 'Custom value'
export const Customer = 'Customer'
export const Dashboard = 'Dashboard'
export const Day = 'Day'
export const Days = 'Days'
export const Danger = 'Danger'
export const Delete = 'Delete'
export const Delivery = 'Delivery'
export const DeliveryIn = 'Your order will be delivered within'
export const DeliverTrack = 'Delivery Tracking'
export const Description = 'Description'
export const Desktop = 'Desktop'
export const Details = 'Details'
export const DidYouMean = 'Did you mean'
export const DirectLinkPayment = 'Direct link to payment'
export const Discount = 'Discount'
export const DiscountOf = 'Discount of'
export const DiscountValue = 'Discount value, percentage or fixed'
export const DisplayName = 'Display name'
export const DocCountry = 'Country of document origin'
export const DocNumber = 'Document number'
export const Docs = 'Docs'
export const DoPaymentMsg = 'Please finalize the payment to confirm your purchase'
export const Edit = 'Edit'
export const EditAdditionalCost = 'Edit additional cost'
export const EditComments = 'Edit comments'
export const EditDispatchAndFulfillment = 'Edit dispatch and fulfillment'
export const EditObservationInfo = 'Edit observation info'
export const EditPaymentDetails = 'Edit payment details'
export const Email = 'Email'
export const EmailAddress = 'Email address'
export const EmailCartText = 'You can finish it now, while the cart is available.'
export const EmailCartTitle = 'You did not finish your purchase!'
export const EmailDeliveredText = 'We hope you have enjoyed shopping with us and will soon visit our website again. The order was delivered to the address below'
export const EmailDeliveredTitle = 'Your package was delivered!'
export const EmailInfo = 'Any update to the order will be notified by email, you can also track the progress through'
export const EmailMarketing = 'Email marketing'
export const EmailShippedText = 'Your package is now with the carrier. To track the delivery progress, go to'
export const EmailShippedTitle = 'Your package is on the way!'
export const EmptyCart = 'Your shopping cart is empty'
export const Enabled = 'Enabled'
export const Endpoint = 'Endpoint'
export const EnterYourDocNumber = 'Enter your document number to confirm'
export const EnterYourEmail = 'Enter your email to proceed'
export const Erp = 'ERP'
export const Events = 'Events'
export const Extra = 'Extra'
export const External = 'External'
export const FamilyName = 'Last name'
export const FeaturedApps = 'Featured apps'
export const Female = 'Female'
export const Field = 'Field'
export const FinancialStatus = 'Financial status'
export const FollowingAddress = 'To the following address'
export const Free = 'Free'
export const FreeShipping = 'Free shipping'
export const Freight = 'Freight'
export const From = 'From'
export const FulfillmentStatus = 'Fulfillment status'
export const FullName = 'Full name'
export const Gateway = 'Gateway'
export const Gender = 'Gender'
export const GenderX = 'Other'
export const GenerateBillet = 'Generate billet'
export const GiftList = 'Add gift options'
export const GiftsListInfo = 'Informations about this customer gift list'
export const GiftsListInfoAuthors = 'Authors of the list'
export const GiftsListInfoContact = 'Email address or phone number to contact list owners'
export const GiftsListInfoDescription = 'Short text description for the gift list'
export const GiftsListInfoEventDate = 'Date and time of the event '
export const GiftsListInfoNotification = 'Email address to be notified after gift purchase'
export const GiftsListInfoPermalink = 'URL to gift list page'
export const GiftsListInfoTitle = 'Title for the gift list'
export const GiftsListInfoValidThru = 'Validity of the list, until this date the gifts can be bought'
export const GiftListOwnerID = 'Specify customer ID who will receive the gift'
export const GiftListWaiting = 'Wait giftlist for purchase'
export const GitRepository = 'Github repository'
export const GivenName = 'Given name'
export const GoToStore = 'Go to store'
export const GoogleProductCategoryId = 'Google product category ID'
export const GridId = 'Grid ID'
export const Grids = 'Grids'
export const GridName = 'Grid name'
export const Hello = 'Hello'
export const HelloAgain = 'Hello again'
export const Help = 'Help'
export const Helpful = 'Helpful'
export const High = 'High'
export const HighPriority = 'High priority'
export const HolderName = 'Holder name'
export const Home = 'Home'
export const Icon = 'Icon'
export const Id = 'ID'
export const Identification = 'Identification'
export const IdentifyAccount = 'Identify your account'
export const In = 'In'
export const Inactive = 'Inactive'
export const Info = 'Information'
export const InscriptionNumber = 'Inscription number'
export const Install = 'Install'
export const InstallNow = 'Install now'
export const InStock = 'In Stock'
export const InStockAt = 'In Stock At'
export const InterestFree = 'Interest free'
export const Intermediator = 'Intermediator'
export const InvalidCard = 'Invalid card info'
export const InvalidCardMsg = 'Unable to validate this card, please check the data or try again later'
export const InvalidLoginInfo = 'Invalid login info, please verify'
export const IsFilter = 'Filter results'
export const IsNotYou = 'Is not you'
export const Item = 'Item'
export const Items = 'Items'
export const Keywords = 'Keywords'
export const Last = 'Last'
export const LastOptions = 'Last available options'
export const LastSearchedTerms = 'Last searched terms'
export const LastVisitedProducts = 'List of last products visited by customer'
export const Launch = 'Launch'
export const Launching = 'Launching'
export const LineAddress = 'Full address'
export const List = 'List'
export const ListPayments = 'List payments'
export const Load = 'Load'
export const Locale = 'Customer language (pt_br)'
export const Login = 'Login'
export const LoginEnabled = 'Login enabled'
export const LoginError = 'There was an error trying to login, please try again or select another option'
export const Logo = 'Logo'
export const Logout = 'Logout'
export const LoyaltyPoints = 'Loyalty points'
export const MadeBy = 'Made by'
export const MainEmail = 'Main email'
export const Male = 'Male'
export const ManageYourHistory = 'Manage your purchase history'
export const Marketing = 'Marketing'
export const Media = 'Media'
export const MediaGallery = 'Media gallery'
export const Marketplace = 'Marketplace'
export const Marketplaces = 'Marketplaces'
export const MetaTagDescription = 'Meta description tag'
export const MiddleName = 'Middle name'
export const MlCategoryId = 'ML Category ID'
export const Mobile = 'Mobile'
export const MobileLink = 'Specific to mobile devices'
export const Modules = 'Modules'
export const Month = 'Month'
export const MostPop = 'Most Popular'
export const MyAccount = 'My account'
export const MyCart = 'My cart'
export const MyOrders = 'My orders'
export const Name = 'Name'
export const NameOnCard = 'Name on card'
export const NearTo = 'Reference for this address'
export const New = 'New'
export const Next = 'Next'
export const Nickname = 'Nickname'
export const NewAddress = 'New address'
export const NoAdditional = 'No additional'
export const NoResultsFor = 'No results for'
export const Normal = 'Normal'
export const Notifications = 'Notifications'
export const NotifyAboutOrders = 'Notify about progress of the order'
export const Notes = 'Additional info'
export const NoNumber = 'No number'
export const Number = 'Number'
export const OauthOnPopup = 'Login in to pop-up'
export const Of = 'Of'
export const OfDiscount = 'Of discount'
export const OnFreight = 'On freight'
export const OnFollowingAddress = 'On the following address'
export const Option = 'Option'
export const Options = 'Options'
export const Order = 'Order'
export const OrderDetails = 'Order details'
export const Orders = 'Orders'
export const OrderCreated = 'Order created'
export const OrderConfirmationMsg = 'Your order has been confirmed, thanks for your preference'
export const OrdersCount = 'Total orders'
export const OrderItems = 'Order items'
export const OrderNumber = 'Order number'
export const OrderStatus = 'Order status'
export const OrderValue = 'Order value'
export const OrdersTotalValue = 'Total orders amount completed'
export const OrProceedWith = 'Or proceed with'
export const OtherCustomers = 'Available to any customers'
export const OutOfStock = 'Sold Out'
export const PageLoaded = 'Page loaded'
export const Paid = 'Paid'
export const PaidText = 'We are already separating your package. Soon will be sent.'
export const ParcelIn = 'Parcel in'
export const ParentCategory = 'Parent category'
export const Partner = 'Partner'
export const Partners = 'Partners'
export const PartnersProgram = 'Partners program'
export const Payment = 'Payment'
export const PaymentConfirmed = 'Payment Confirmed'
export const PaymentDetails = 'Payment details'
export const PaymentError = 'Payment error'
export const PaymentErrorMsg = 'Unable to approve purchase, please verify details or try another payment method'
export const PaymentLink = 'Payment link'
export const PaymentMethod = 'Payment method'
export const PaymentMethodLabel = 'Payment method label'
export const PaymentRealized = 'Payment realized'
export const PersonalRegistration = 'Personal registration'
export const Permalink = 'Permalink'
export const Phone = 'Phone'
export const Phones = 'Phones'
export const Photo = 'Photo'
export const Photos = 'Photos'
export const Pickup = 'Pickup'
export const Picture = 'Picture'
export const Pictures = 'Pictures'
export const Popup = 'Popup'
export const Post = 'Post'
export const Posted = 'Posted'
export const PostingIn = 'Products will be ship within'
export const Price = 'Price'
export const Pricing = 'Pricing'
export const PrintBillet = 'Print billet'
export const Privacy = 'Privacy'
export const PrivacyPolicy = 'Privacy policy'
export const Product = 'Product'
export const Products = 'Products'
export const ProductsPurchased = 'Products purchased by customer'
export const ProfileNotFound = 'No profile found with email address'
export const Province = 'Province or state name'
export const ProvinceCode = 'Province code'
export const Quantity = 'Quantity'
export const Rating = 'Rating'
export const Read = 'Read'
export const ReceivedOrder = 'Received your order!'
export const ReceiveNewsletter = 'Receive newsletter'
export const Recipient = 'Recipient'
export const RedirectToPayment = 'Redirect to payment'
export const Reference = 'Reference'
export const Referral = 'Customer invided by'
export const ReferringSite = 'Referring site'
export const RegisterToBuy = 'Complete your registration to proceed with the purchase'
export const Registration = 'Registration'
export const RelatedSearch = 'Related search items'
export const RelatedProduct = 'Related products'
export const Remove = 'Remove'
export const ResultsFor = 'Results for'
export const Retail = 'Retail'
export const Reviews = 'Customer reviews'
export const Sales = 'Sales'
export const SalesChannels = 'Sales channels'
export const Save = 'Save'
export const Saved = 'Saved'
export const Search = 'Search'
export const SecurityCode = 'Security code'
export const SeeAll = 'See all'
export const SeeAllApps = 'See all apps'
export const SeeAllThemes = 'See all themes'
export const SeeCart = 'See shopping cart'
export const SeeMoreCategories = 'See more categories'
export const SeeMoreInfo = 'See more info'
export const SeeOrder = 'See order'
export const SellerRecommendations = 'Seller recommendations'
export const SellerRecommendationsProducts = 'Seller recommendation products'
export const SellerRecommendationsTitle = 'Seller recommendation title'
export const Seo = 'SEO'
export const ShareWhats = 'Share in to Whatsapp'
export const Shipped = 'Shipped'
export const ShippedBy = 'Shipped by'
export const ShippingAddress = 'Shipping address'
export const ShippingMethod = 'Shipping options'
export const ShippingMethodLabel = 'Shipping method label'
export const ShopByCategory = 'Shop by category'
export const ShopByFranchise = 'Shop by franchise'
export const ShopNow = 'Shop now'
export const ShoppingCart = 'Shopping cart'
export const Short = 'Short'
export const ShortDescription = 'Short description'
export const Show = 'Show'
export const ShowDescription = 'Show full description'
export const ShowReview = 'Show full review'
export const SignInWith = 'Sign in with'
export const SignIn = 'Sign in'
export const SignUpWith = 'Sign up with'
export const SignUp = 'Sign Up'
export const Size = 'Size'
export const Sku = 'Sku'
export const Slug = 'Slug (URL)'
export const SocialLogin = 'Social login'
export const SocialMedia = 'Social media'
export const Source = 'Source'
export const Sort = 'Sort'
export const SortBy = 'Sort by'
export const StaffNotes = 'Staff notes'
export const StaffSignature = 'Created by staff'
export const Star = 'Star'
export const State = 'State'
export const Status = 'Status'
export const Street = 'Street'
export const Store = 'Store'
export const Storefront = 'Storefront'
export const Subtitle = 'Subtitle for SEO purpose'
export const Subtotal = 'Subtotal'
export const Success = 'Success'
export const Summary = 'Summary'
export const Support = 'Support'
export const TaxExempt = 'Tax'
export const TermSearched = 'Term searched'
export const Test = 'Test'
export const Thanks = 'Thanks!'
export const ThanksForPurchase = 'Thank you for your purchase'
export const Theme = 'Theme'
export const Themes = 'Themes'
export const TicketCode = 'Ticket code'
export const Title = 'Title'
export const TitleTag = 'Title tag'
export const To = 'To'
export const Today = 'Today'
export const Token = 'Token'
export const Total = 'Total'
export const TotalCancelled = 'Total cancelled'
export const TotalResultsFor = 'Products found for'
export const TotalSpent = 'Total spent by custumer'
export const TransactionCode = 'Transaction code'
export const TrendingApps = 'Trending apps'
export const Type = 'Type'
export const Unavailable = 'Unavailable'
export const Uninstall = 'Uninstall'
export const Unlimited = 'Unlimited'
export const Unsub = 'Unsubscribe'
export const Update = 'Update'
export const UpTo = 'Up to'
export const Username = 'Username'
export const Utm = 'Utm'
export const UtmCampaign = 'Utm campaign'
export const UtmContent = 'Utm content'
export const UtmMedium = 'Utm medium'
export const UtmSource = 'Utm source'
export const UtmTerm = 'Utm term'
export const Url = 'Url'
export const ValidThru = 'Valid thru'
export const Value = 'Value'
export const Verified = 'Verified'
export const Version = 'Version'
export const VersionDate = 'Version date'
export const Visitor = 'Visitor'
export const VisitorCheckout = 'You can also buy as a visitor if you prefer'
export const Warning = 'Warning'
export const WasAnErrorOnLogin = 'There was an error trying to login, please try again or select another option'
export const WeFrom = 'We from'
export const Welcome = 'Welcome'
export const WelcomeText = 'We are happy with your registration. Take a look at our products!'
export const WeUseYourDataTo = 'We will use your data safely and responsibly to'
export const Widgets = 'Widgets'
export const WillReceiveMsg = 'You\'ll receive the products in up to'
export const Write = 'Write'
export const WriteReview = 'Write a review'
export const WorkingDays = 'Working days'
export const Year = 'Year'
export const ZipCode = 'Zip Code'

export const _FinancialStatus = {
  pending: 'Pending payment',
  under_analysis: 'Payment under analysis',
  authorized: 'Authorized payment',
  unauthorized: 'Unauthorized payment',
  partially_paid: 'Partially paid',
  paid: 'Paid',
  dispute: 'Payment in dispute',
  partially_refunded: 'Payment partially refunded',
  refunded: 'Payment refunded',
  voided: 'Payment voided',
  unknown: 'Unknown payment status'
}
export const _FinancialStatusMsg = {
  pending: 'Your order have',
  under_analysis: 'Your order have',
  authorized: 'Your order have',
  unauthorized: 'Your order have',
  partially_paid: 'Your order is',
  paid: 'Your order have',
  dispute: 'Your order have',
  partially_refunded: 'Your order have',
  refunded: 'Your order have',
  voided: 'Your order have',
  unknown: 'Your order have'
}
export const _OrderStatus = {
  open: 'Open order',
  closed: 'Finalized order',
  cancelled: 'Cancelled'
}
export const _FulfillmentStatus = {
  ready_for_shipping: 'Ready for shipping',
  shipped: 'Shipped',
  delivered: 'Delivered',
  invoice_issued: 'Invoice issued',
  in_production: 'In production',
  in_separation: 'In separation',
  partially_shipped: 'Partially shipped',
  partially_delivered: 'Partially delivered',
  returned_for_exchange: 'Returned for exchange',
  received_for_exchange: 'Received for exchange',
  returned: 'Returned'
}
export const _FulfillmentStatusMsg = {
  ready_for_shipping: 'Your order is',
  shipped: 'Your order was',
  delivered: 'Your order was',
  invoice_issued: 'Your',
  in_production: 'Your order is',
  in_separation: 'Your order is',
  partially_shipped: 'Your order was',
  partially_delivered: 'Your order was',
  returned_for_exchange: 'Your order had',
  received_for_exchange: 'Your order was',
  returned: 'Your order was'
}
export const _modules = {
  pageLoaded: 'Page loaded',
  termSearched: 'Term searched',
  cartConfirmed: 'Cart confirmed',
  calculateShipping: 'Calculate shipping',
  listPayments: 'List payments',
  applyDiscount: 'Apply discount',
  createTransaction: 'Create transaction',
  checkoutDone: 'Checkout done'
}
export const _discountApplyAt = {
  total: 'Total',
  subtotal: 'Subtotal',
  freight: 'Freight'
}
export const _discountType = {
  percentage: 'Percentage',
  fixed: 'Fixed'
}
export const _stateRegister = {
  invited: 'invited',
  registered: 'registered',
  declined: 'declined'
}
export const _phoneType = {
  home: 'home',
  personal: 'personal',
  work: 'word',
  other: 'other'
}
export const _registryType = {
  p: 'Physical',
  j: 'Juridical'
}
export const _inscriptionType = {
  state: 'State',
  municipal: 'Municipal'
}
