export const AboutCvv = '3 or 4 digits, usually on the back of the card (up front on AMEX cards)'
export const AcceptAttachedFile = 'Accept attached file'
export const AcceptCustomOptionByCustomer = 'Accept custom option by customer'
export const Active = 'Active'
export const Add = 'Add'
export const Additional = 'Additional'
export const Addresses = 'Addresses'
export const AddPref = 'Add to preferences'
export const AddToPrice = 'Add to price'
export const AdminSettings = 'Admin Settings'
export const Advanced = 'Advanced'
export const AffiliateCoede = 'Afiliate code'
export const AllCategories = "All categories"
export const Alt = 'Alt tag'
export const AlterationPrice = 'Default price alteration on products with this grid for customization or variations.'
export const Another = 'Another'
export const ApplyDiscount = 'Apply discount'
export const AtSight = 'At sight'
export const Attachment = 'Attachment'
export const Authentication = 'Authentication'
export const Available = 'Available to buy'
export const AvailableApps = "Available apps"
export const BackToCart = 'Back to cart'
export const Bag = 'Bag'
export const Banner = 'Banner'
export const Banners = 'Banners'
export const Birthdate = 'Birthdate'
export const Borough = 'Borough'
export const Buy = 'Buy'
export const Buyer = 'Buyer'
export const By = 'by'
export const Brand = 'Brand'
export const BrandName = 'Brand name'
export const BuyWith = 'Frequently bought together'
export const CalculateShipping = 'Calculate shipping'
export const Callback = 'callback'
export const CardNumber = 'Card number'
export const CartConfirmed = 'Cart confirmed'
export const CartItems = 'Cart items'
export const Category = 'Category'
export const CategoryBanners = 'Category banner'
export const CategoryName = 'Category name'
export const Cellphone = 'Cellphone'
export const ChangePaymentMethod = 'Change payment method'
export const ChangeShippingMethod = 'Change shipping method'
export const Channel = 'Channel'
export const Channels = 'Channels'
export const Checkout = 'Checkout'
export const CheckoutEnabled = 'Checkout enabled'
export const CheckoutDone = 'Checkout done'
export const City = 'City'
export const Close = 'Close'
export const Code = 'Code'
export const CodeCopied = 'Code copied'
export const Collection = 'Collection'
export const Collections = 'Collections'
export const CollectionBanners = 'Collection banner'
export const CollectionItems = 'Collection items'
export const CollectionName = 'Collection name'
export const Color = 'Color'
export const Colors = 'Colors'
export const CompanyRegistration = 'Company registration'
export const CompareProducts = 'Compare with similar items'
export const Complement = 'Complement'
export const ComplementInformation = 'Complement Information'
export const ConfirmPurchase = 'Confirm purchase'
export const ContactPhone = 'Contact phone'
export const Content = 'Content'
export const Continue = 'Continue'
export const ContinueShopping = 'Continue shopping'
export const Control = 'Control'
export const CopyCode = 'Copy code'
export const CopyErrorMsg = 'Error copying to clipboard, please copy manually'
export const CountryCode = 'Country code'
export const CreateTransaction = 'Create transaction'
export const Creation = 'Creation'
export const Custom = 'Customize'
export const CustomValue = 'Custom value'
export const Customer = 'Customer'
export const Dashboard = 'Dashboard'
export const Day = 'Day'
export const Days = 'Days'
export const Danger = 'Danger'
export const Delete = 'Delete'
export const Delivery = 'Delivery'
export const DeliverTrack = 'Delivery Tracking'
export const Description = 'Description'
export const DidYouMean = 'Did you mean'
export const Discount = 'Discount'
export const DiscountOf = 'Discount of'
export const DisplayName = 'Display name'
export const DocNumber = 'Document number'
export const DoPaymentMsg = 'Please finalize the payment to confirm your purchase'
export const Edit = 'Edit'
export const EditAdditionalCost = 'Edit additional cost'
export const EditDispatchAndFulfillment = 'Edit dispatch and fulfillment'
export const EditObservationInfo = 'Edit observation info'
export const Email = 'Email'
export const EmailAddress = 'Email address'
export const EmptyCart = 'Your shopping cart is empty'
export const Enabled = 'Enabled'
export const Endpoint = 'Endpoint'
export const EnterYourDocNumber = 'Enter your document number to confirm'
export const EnterYourEmail = 'Enter your email to proceed'
export const Events = 'Events'
export const External = 'External'
export const FamilyName = 'Last name'
export const Female = 'Female'
export const Field = 'Field'
export const Free = 'Free'
export const FreeShipping = 'Free shipping'
export const Freight = 'Freight'
export const From = 'From'
export const FullName = 'Full name'
export const Gender = 'Gender'
export const GenderX = 'Other'
export const GenerateBillet = 'Generate billet'
export const GiftListOwnerID = 'Specify customer ID who will receive the gift'
export const GiftOption = 'Add gift options'
export const GitRepository = 'Github repository'
export const GivenName = 'Given name'
export const GoogleProductCategoryId = 'Google product category ID'
export const GridId = 'Grid ID'
export const Grids = 'Grids'
export const GridName = 'Grid name'
export const Hello = 'Hello'
export const HelloAgain = 'Hello again'
export const HolderName = 'Holder name'
export const Home = 'Home'
export const Icon = 'Icon'
export const Id = 'ID'
export const Identification = 'Identification'
export const IdentifyAccount = 'Identify your account'
export const Inactive = 'Inactive'
export const Info = 'Information'
export const InvalidCard = 'Invalid card info'
export const InvalidCardMsg = 'Unable to validate this card, please check the data or try again later'
export const InvalidLoginInfo = 'Invalid login info, please verify'
export const InterestFree = 'Interest free'
export const Install = 'Install'
export const InStock = 'In Stock'
export const InStockAt = 'In Stock At'
export const IsFilter = 'Filter results'
export const IsNotYou = 'Is not you'
export const Item = 'Item'
export const Items = 'Items'
export const Last = 'Last'
export const LastOptions = 'Last available options'
export const List = 'List'
export const ListPayments = 'List payments'
export const Load = 'Load'
export const Locale = 'Customer language (pt_br)'
export const Login = 'Login'
export const LoginEnabled = 'Login enabled'
export const LoginError = 'There was an error trying to login, please try again or select another option'
export const Logo = 'Logo'
export const Logout = 'Logout'
export const MainEmail = 'Main email'
export const Male = 'Male'
export const ManageYourHistory = 'Manage your purchase history'
export const MetaTagDescription = 'Meta description tag'
export const MiddleName = 'Middle name'
export const MlCategoryId = 'ML Category ID'
export const MobileLink = 'Specific to mobile devices'
export const Modules = 'Modules'
export const Month = 'Month'
export const MostPop = 'Most Popular'
export const MyAccount = 'My account'
export const MyCart = 'My cart'
export const MyOrders = 'My orders'
export const Name = 'Name'
export const NameOnCard = 'Name on card'
export const New = 'New'
export const Nickname = 'Nickname'
export const NewAddress = 'New address'
export const NoAdditional = 'No additional'
export const NoResultsFor = 'No results for'
export const Normal = 'Normal'
export const Notifications = 'Notifications'
export const NotifyAboutOrders = 'Notify about progress of the order'
export const Notes = 'Additional info'
export const NoNumber = 'No number'
export const Number = 'Number'
export const OauthOnPopup = 'Login in to pop-up'
export const Of = 'Of'
export const OfDiscount = 'Of discount'
export const OnFreight = 'On freight'
export const Options = 'Options'
export const Orders = 'Orders'
export const OrderCreated = 'Order created'
export const OrderConfirmationMsg = 'Your order has been confirmed, thanks for your preference'
export const OrderNumber = 'Order number'
export const OrProceedWith = 'Or proceed with'
export const OtherCustomers = 'Available to any customers'
export const OutOfStock = 'Sold Out'
export const PageLoaded = 'Page loaded'
export const Paid = 'Paid'
export const ParcelIn = 'Parcel in'
export const ParentCategory = 'Parent category'
export const Payment = 'Payment'
export const PaymentConfirmed = 'Payment Confirmed'
export const PaymentRealized = 'Payment realized'
export const PaymentError = 'Payment error'
export const PaymentErrorMsg = 'Unable to approve purchase, please verify details or try another payment method'
export const PersonalRegistration = 'Personal registration'
export const Permalink = 'Permalink'
export const Phone = 'Phone'
export const Phones = 'Phones'
export const Photo = 'Photo'
export const Photos = 'Photos'
export const Pickup = 'Pickup'
export const Picture = 'Picture'
export const Pictures = 'Pictures'
export const Price = 'Price'
export const PrintBillet = 'Print billet'
export const Product = 'Product'
export const Products = 'Products'
export const ProfileNotFound = 'No profile found with email address'
export const ProvinceCode = 'Province code'
export const Quantity = 'Quantity'
export const Read = 'Read'
export const ReceiveNewsletter = 'Receive newsletter'
export const Recipient = 'Recipient'
export const RedirectToPayment = 'Redirect to payment'
export const Reference = 'Reference'
export const Referral = 'Customer invided by'
export const ReferringSite = 'Referring site'
export const RegisterToBuy = 'Complete your registration to proceed with the purchase'
export const Registration = 'Registration'
export const RelatedSearch = 'Related search items'
export const RelatedProduct = 'Related products'
export const Remove = 'Remove'
export const ResultsFor = 'Results for'
export const Reviews = 'Customer reviews'
export const Save = 'Save'
export const SecurityCode = 'Security code'
export const SeeAll = 'See all'
export const Search = 'Search'
export const SeeCart = 'See shopping cart'
export const SeeMoreCategories = 'See more categories'
export const SeeMoreInfo = 'See more info'
export const ShareWhats = 'Share in to Whatsapp'
export const Shipped = 'Shipped'
export const ShippingMethod = 'Shipping options'
export const ShopByCategory = 'Shop by category'
export const ShopByFranchise = 'Shop by franchise'
export const ShopNow = 'Shop now'
export const ShoppingCart = 'Shopping cart'
export const Short = 'Short'
export const ShortDescription = 'Short description'
export const SignInWith = 'Sign in with'
export const SignIn = 'Sign in'
export const SignUpWith = 'Sign up with'
export const SignUp = 'Sign Up'
export const Size = 'Size'
export const Sku = 'Sku'
export const Slug = 'Slug (URL)'
export const Source = 'Source'
export const StaffSignature = 'Created by staff'
export const State = 'State'
export const Status = 'Status'
export const Street = 'Street'
export const Storefront = 'Storefront'
export const Subtitle = 'Subtitle for SEO purpose'
export const Subtotal = 'Subtotal'
export const Success = 'Success'
export const Summary = 'Summary'
export const TermSearched = 'Term searched'
export const Test = 'Test'
export const TicketCode = 'Ticket code'
export const Title = 'Title'
export const TitleTag = 'Title tag'
export const To = 'To'
export const Today = 'Today'
export const Total = 'Total'
export const TotalResultsFor = 'Products found for'
export const Type = 'Type'
export const Unavailable = 'Unavailable'
export const Update = 'Update'
export const UpTo = 'Up to'
export const Username = 'Username'
export const Utm = 'Utm'
export const UtmCampaign = 'Utm campaign'
export const UtmContent = 'Utm content'
export const UtmMedium = 'Utm medium'
export const UtmSource = 'Utm source'
export const UtmTerm = 'Utm term'
export const Url = 'Url'
export const ValidThru = 'Valid thru'
export const Value = 'Value'
export const Version = 'Version'
export const VersionDate = 'Version date'
export const Visitor = 'Visitor'
export const VisitorCheckout = 'You can also buy as a visitor if you prefer'
export const Warning = 'Warning'
export const WasAnErrorOnLogin = 'There was an error trying to login, please try again or select another option'
export const WeUseYourDataTo = 'We will use your data safely and responsibly to'
export const WillReceiveMsg = 'You\'ll receive the products in up to'
export const WorkingDays = 'Working days'
export const Year = 'Year'
export const YourInstalledApps = 'Your installed apps'
export const ZipCode = 'Zip Code'

export const _FinancialStatus = {
  pending: 'Pending payment',
  under_analysis: 'Payment under analysis',
  authorized: 'Authorized payment',
  unauthorized: 'Unauthorized payment',
  partially_paid: 'Partially paid',
  paid: 'Paid',
  dispute: 'Payment in dispute',
  partially_refunded: 'Payment partially refunded',
  refunded: 'Payment refunded',
  voided: 'Payment voided',
  unknown: 'Unknown payment status'
}
export const _OrderStatus = {
  open: 'Open order',
  closed: 'Finalized order',
  cancelled: 'Cancelled'
}
export const _FulfillmentStatus = {
  ready_for_shipping: 'Ready for shipping',
  shipped: 'Shipped',
  delivered: 'Delivered'
}
export const _modules = {
  pageLoaded: 'Page loaded',
  termSearched: 'Term searched',
  cartConfirmed: 'Cart confirmed',
  calculateShipping: 'Calculate shipping',
  listPayments: 'List payments',
  applyDiscount: 'Apply discount',
  createTransaction: 'Create transaction',
  checkoutDone: 'Checkout done'
}
export const _discountApplyAt = {
  total: 'Total',
  subtotal: 'Subtotal',
  freight: 'Freight'
}
export const _discountType = {
  percentage: 'Percentage',
  fixed: 'Fixed'
}
export const _stateRegister = {
  invited: 'invited',
  registered: 'registered',
  declined: 'declined'
}
export const _phoneType = {
  home: 'home',
  personal: 'personal',
  work: 'word',
  other: 'other'
}
export const _registryType = {
  p: 'Physical',
  j: 'Juridical'
}