export const i19about = 'Sobre nós'
export const i19aboutCvv = '3 ou 4 dígitos, geralmente no verso do cartão (na frente em cartões AMEX)'
export const i19acceptAttachedFile = 'Aceitar arquivo em anexo'
export const i19acceptCustomOptionByCustomer = 'Aceitar opção personalizada pelo cliente'
export const i19active = 'Ativo'
export const i19add = 'Adicionar'
export const i19addApp = 'Adicionar aplicativo'
export const i19addCart = 'Adicionar ao carrinho'
export const i19addClient = 'Adicionar Cliente'
export const i19additional = 'Adicional'
export const i19additionalCost = 'Custo adicional'
export const i19address = 'Endereço'
export const i19addresses = 'Endereços'
export const i19addressesName = 'Destinatário'
export const i19addPref = 'Adicionar aos desejos'
export const i19addToPrice = 'Adicionar preço'
export const i19adminSettings = 'Configurações no painel'
export const i19advanced = 'Avançado'
export const i19affiliateCoede = 'Código do afiliado'
export const i19afterPayment = 'Após a confirmação do pagamento'
export const i19alt = 'Tag alt'
export const i19alterationPrice = 'Alteração padrão de preço nos produtos com essa grade para personalização ou variações.'
export const i19another = 'Outro'
export const i19app = 'Aplicativo'
export const i19appDevelopers = 'Desenvolvedor de aplicativos'
export const i19applyDiscount = 'Aplicar desconto'
export const i19atSight = 'À vista'
export const i19attachment = 'Anexar'
export const i19authentication = 'Autenticação'
export const i19available = 'Disponível para compra'
export const i19backToCart = 'Voltar ao carrinho'
export const i19bag = 'Sacola'
export const i19banner = 'Banner'
export const i19banners = 'Banners'
export const i19birthdate = 'Data de nascimento'
export const i19billingAddress = 'Endereço de cobrança'
export const i19borough = 'Bairro'
export const i19buy = 'Comprar'
export const i19buyer = 'Comprador'
export const i19by = 'Por'
export const i19brand = 'Marca'
export const i19brandName = 'Nome da marca'
export const i19brazil = 'Brasil'
export const i19buyWith = 'Comprar Juntos'
export const i19calculateShipping = 'Calcular frete e prazo'
export const i19callback = 'Callback'
export const i19cancel = 'Cancelar'
export const i19cancelled = 'Cancelado'
export const i19cardNumber = 'Número do cartão'
export const i19cartConfirmed = 'Carrinho confirmado'
export const i19cartDetails = 'Detalhes do carrinho'
export const i19cartItems = 'Itens do Carrinho'
export const i19category = 'Categoria'
export const i19categoryBanners = 'Banner da categoria'
export const i19categoryName = 'Nome da categoria'
export const i19cellphone = 'Celular'
export const i19changePaymentMethod = 'Alterar forma de pagamento'
export const i19changeShippingMethod = 'Alterar forma de envio'
export const i19channel = 'Canal'
export const i19channels = 'Canais'
export const i19checkout = 'Finalizar compra'
export const i19checkoutEnabled = 'Checkout habilitado'
export const i19checkoutDone = 'Checkout finalizado'
export const i19city = 'Cidade'
export const i19close = 'Fechar'
export const i19code = 'Código'
export const i19codeCopied = 'Código copiado'
export const i19collection = 'Coleção'
export const i19collections = 'Coleções'
export const i19collectionBanners = 'Banner da coleção'
export const i19collectionItems = 'Itens da coleção'
export const i19collectionName = 'Nome da coleção'
export const i19color = 'Cor'
export const i19colors = 'Cores'
export const i19community = 'Comunidade'
export const i19companyRegistration = 'Pessoa jurídica'
export const i19compareProducts = 'Produtos Similares'
export const i19complement = 'Complemento'
export const i19complementInformation = 'Informação complementar'
export const i19confirmPurchase = 'Confirmar compra'
export const i19contactPhone = 'Telefone de contato'
export const i19contactUs = 'Se houver alguma dúvida entre em contato conosco.'
export const i19content = 'Conteúdo'
export const i19continue = 'Continuar'
export const i19continueShopping = 'Continuar comprando'
export const i19control = 'Controle'
export const i19copyCode = 'Copiar código'
export const i19copyErrorMsg = 'Erro ao copiar para a área de transferência, por favor copie manualmente'
export const i19corporateName = 'Razão sozial da empresa'
export const i19countryCode = 'Código do país'
export const i19createTransaction = 'Criar a transação'
export const i19creation = 'Criação'
export const i19credit = 'Crédito'
export const i19creditCard = 'Cartão de credito'
export const i19creditCardBin = 'Número de indetificação do cartão'
export const i19creditCardCompany = 'Emissora do cartao'
export const i19creditCardHolderName = 'Nome no cartão'
export const i19creditCardLastDigits = 'Últimos dígitos do cartão'
export const i19currencyId = 'Identificador da moeda'
export const i19currencySymbol = 'Símbolo monetário'
export const i19custom = 'Personalização'
export const i19customValue = 'Opção personalizada'
export const i19customer = 'Cliente'
export const i19dashboard = 'Painel'
export const i19day = 'Dia'
export const i19days = 'Dias'
export const i19danger = 'Perigo'
export const i19delete = 'Deletar'
export const i19delivery = 'Entrega'
export const i19deliveryIn = 'Seu pedido será entregue em até'
export const i19deliverTrack = 'Rastreamento de pedido'
export const i19description = 'Descrição'
export const i19desktop = 'Desktop'
export const i19details = 'Detalhes'
export const i19didYouMean = 'Você quis dizer'
export const i19directLinkPayment = 'Link para pagamento'
export const i19discount = 'Desconto'
export const i19discountOf = 'Desconto de'
export const i19discountValue = 'Desconto fixo, percentual ou por valor'
export const i19displayName = 'Apelido'
export const i19docCountry = 'País de emissão do documento'
export const i19docNumber = 'Número do documento'
export const i19docs = 'Documentação'
export const i19doPaymentMsg = 'Por favor finalize o pagamento para confirmar sua compra'
export const i19edit = 'Editar'
export const i19editAdditionalCost = 'Editar custo adicional'
export const i19editComments = 'Editar configuração'
export const i19editDispatchAndFulfillment = 'Editar envio e atendimento'
export const i19editObservationInfo = 'Editar observação do cliente'
export const i19editPaymentDetails = 'Editar detalhes do pagamento'
export const i19email = 'E-mail'
export const i19emailAddress = 'Endereço de e-mail'
export const i19emailCartText = 'Você pode concluí-la agora, enquanto o carrinho ainda está disponível. Não perca essa chance!'
export const i19emailCartTitle = 'Você não finalizou sua compra!'
export const i19emailDeliveredText = 'Esperamos que tenha gostado da experiência de compra e em breve visite novamente nosso site. O pedido foi entregue no endereço abaixo'
export const i19emailDeliveredTitle = 'Sua compra foi entregue!'
export const i19emailInfo = 'Qualquer atualização no pedido será notificada por e-mail, você também pode acompanhar o andamento pela página'
export const i19emailMarketing = 'E-mail marketing'
export const i19emailShippedText = 'Seu pacote já foi entregue para a transportadora. Para acompanhar o andamento da entrega acesse a página'
export const i19emailShippedTitle = 'Seu pedido está a caminho!'
export const i19emptyCart = 'Seu carrinho de compras está vazio'
export const i19enabled = 'Habilitado'
export const i19endpoint = 'Endpoint'
export const i19enterYourDocNumber = 'Confirme o login com seu documento'
export const i19enterYourEmail = 'Informe seu email para prosseguir'
export const i19erp = 'ERP'
export const i19events = 'Eventos'
export const i19extra = 'Extra'
export const i19external = 'Externo'
export const i19familyName = 'Último nome'
export const i19featuredApps = 'Aplicativos em destaque'
export const i19female = 'Feminino'
export const i19field = 'Campo'
export const i19financialStatus = 'Status financeiro'
export const i19followingAddress = 'Para o endereço abaixo'
export const i19free = 'Grátis'
export const i19freeShipping = 'Frete grátis'
export const i19freight = 'Frete'
export const i19from = 'De'
export const i19fulfillmentStatus = 'Status de entrega'
export const i19fullName = 'Full name'
export const i19gateway = 'Gateway'
export const i19gender = 'Gênero'
export const i19genderX = 'Outros'
export const i19generateBillet = 'Gerar boleto'
export const i19giftList = 'Adicionar na lista de presentes'
export const i19giftsListInfo = 'Informações da lista de presente'
export const i19giftsListInfoAuthors = 'Criadores da lista de presente'
export const i19giftsListInfoContact = 'Contato do criador da lista de presente'
export const i19giftsListInfoDescription = 'Descrição da lista de presente'
export const i19giftsListInfoEventDate = 'Data do evento'
export const i19giftsListInfoNotification = 'E-mail de produtos comprados da lista de presente'
export const i19giftsListInfoPermalink = 'Link permanente da lista'
export const i19giftsListInfoTitle = 'Título da lista de presente'
export const i19giftsListInfoValidThru = 'Validade da lista de presente'
export const i19giftListOwnerID = 'Especificar ID do cliente que receberá presente'
export const i19giftListWaiting = 'Lista de presente'
export const i19gitRepository = 'Repositório do github'
export const i19givenName = 'Primeiro nome'
export const i19goToStore = 'Ir para a loja'
export const i19googleProductCategoryId = 'ID da categoria no Google'
export const i19gridId = 'ID do grid'
export const i19grids = 'Grids'
export const i19gridName = 'Nome da grade'
export const i19hello = 'Olá'
export const i19helloAgain = 'Olá novamente'
export const i19help = 'Ajuda'
export const i19helpful = 'Útil'
export const i19high = 'Alto'
export const i19highPriority = 'Prioridade máxima'
export const i19holderName = 'Nome do titular'
export const i19home = 'Home'
export const i19icon = 'Ícone'
export const i19id = 'ID'
export const i19identification = 'Identificação'
export const i19identifyAccount = 'Identifique-se ou crie sua conta'
export const i19in = 'Em'
export const i19inactive = 'Inativo'
export const i19info = 'Informação'
export const i19inscriptionNumber = 'Número da inscrição estadual/municipal'
export const i19install = 'Instalar'
export const i19installNow = 'Instalar agora'
export const i19inStock = 'Disponível'
export const i19inStockAt = 'Busque em'
export const i19interestFree = 'Sem juros'
export const i19intermediator = 'Intermediador'
export const i19invalidCard = 'Cartão inválido'
export const i19invalidCardMsg = 'Não foi possível validar este cartão, por favor verifique os dados ou tente novamente mais tarde'
export const i19invalidLoginInfo = 'Login inválido, por favor verifique os dados informados'
export const i19isFilter = 'Resultados do filtro'
export const i19isNotYou = 'Não é você'
export const i19item = 'Item'
export const i19items = 'Itens'
export const i19keywords = 'Palavras chave'
export const i19last = 'Último'
export const i19lastOptions = 'Últimas unidades disponíveis'
export const i19lastSearchedTerms = 'Últimos produtos visitados'
export const i19lastVisitedProducts = 'Últimos produtos visitados pelo cliente'
export const i19launch = 'Lançamento'
export const i19launching = 'Lançando'
export const i19lineAddress = 'Endereço completo'
export const i19list = 'Listar'
export const i19listPayments = 'Listar formas de pagamento'
export const i19load = 'Carregar'
export const i19locale = 'Idioma do cliente (pt_br)'
export const i19login = 'Login'
export const i19loginEnabled = 'Login habilitado'
export const i19loginError = 'Houve um erro ao tentar o login, por favor tente novamente ou tente outra opção'
export const i19logo = 'Logo'
export const i19logout = 'Sair'
export const i19loyaltyPoints = 'Pontos do programa de fidalidade'
export const i19madeBy = 'Feito por'
export const i19mainEmail = 'E-mail principal'
export const i19male = 'Masculino'
export const i19manageYourHistory = 'Gerenciar seu histórico de compras'
export const i19marketing = 'Marketing'
export const i19media = 'Mídia'
export const i19mediaGallery = 'Galeria de imagens'
export const i19metaTagDescription = 'Meta description tag'
export const i19marketplace = 'Marketplace'
export const i19marketplaces = 'Marketplaces'
export const i19middleName = 'Sobrenome do meio'
export const i19mlCategoryId = 'ID da categoria no ML'
export const i19mobile = 'Mobile'
export const i19mobileLink = 'Links específicos para celular'
export const i19modules = 'Módulos'
export const i19month = 'Mês'
export const i19mostPop = 'Mais populares'
export const i19myAccount = 'Minha conta'
export const i19myCart = 'Meu carrinho'
export const i19myOrders = 'Meus pedidos'
export const i19name = 'Nome'
export const i19nameOnCard = 'Nome impresso cartão'
export const i19nearTo = 'Referência do endereço'
export const i19new = 'Novo'
export const i19next = 'Próximo'
export const i19nickname = 'Apelido'
export const i19newAddress = 'Novo endereço'
export const i19noAdditional = 'Sem adicional'
export const i19noResultsFor = 'Nenhum produto encontrado para'
export const i19normal = 'Normal'
export const i19notifications = 'Notificações'
export const i19notifyAboutOrders = 'Notificar sobre o andamento do pedido'
export const i19notes = 'Informação adicional'
export const i19noNumber = 'S/N'
export const i19number = 'Número'
export const i19oauthOnPopup = 'Continue o login no pop-up'
export const i19of = 'De'
export const i19ofDiscount = 'Desconto de'
export const i19onFreight = 'Frete de'
export const i19onFollowingAddress = 'No endereço abaixo'
export const i19option = 'Opção'
export const i19options = 'Opções'
export const i19order = 'Pedido'
export const i19orderDetails = 'Detalhes do pedido'
export const i19orders = 'Pedidos'
export const i19orderCreated = 'Pedido criado'
export const i19orderConfirmationMsg = 'Seu pedido foi confirmado, obrigado pela preferência'
export const i19ordersCount = 'Total de pedidos'
export const i19orderItems = 'Itens do pedido'
export const i19orderNumber = 'Número do pedido'
export const i19orderStatus = 'Status do pedido'
export const i19orderValue = 'Valor do pedido'
export const i19ordersTotalValue = 'Valor total de pedidos completados'
export const i19orProceedWith = 'Ou prossiga com'
export const i19otherCustomers = 'Disponível para outros clientes'
export const i19outOfStock = 'Sem estoque'
export const i19pageLoaded = 'Página carregada'
export const i19paid = 'Pago'
export const i19paidText = 'Recebemos seu pagamento e estamos trabalhando para que você receba seu(s) produto(s) o mais rápido possível'
export const i19parcelIn = 'Parcelar em'
export const i19parentCategory = 'Categoria pai'
export const i19partner = 'Parceiro'
export const i19partners = 'Parceiros'
export const i19partnersProgram = 'Programa de parceiros'
export const i19payment = 'Pagamento'
export const i19paymentConfirmed = 'Pagamento confirmado'
export const i19paymentDetails = 'Detalhes do pagamento'
export const i19paymentError = 'Erro no pagamento'
export const i19paymentErrorMsg = 'Não foi possível aprovar a compra, por favor verifique os dados ou tente com outra forma de pagamento'
export const i19paymentLink = 'Link de pagamento'
export const i19paymentMethod = 'Forma de pagamento'
export const i19paymentMethodLabel = 'Nome da forma de pagamento'
export const i19paymentRealized = 'Pagamento realizado'
export const i19personalRegistration = 'Pessoa física'
export const i19permalink = 'Link permanente'
export const i19phone = 'Telefone'
export const i19phones = 'Telefones'
export const i19photo = 'Foto'
export const i19photos = 'Fotos'
export const i19pickup = 'Coleta'
export const i19picture = 'Imagem'
export const i19pictures = 'Imagens'
export const i19popup = 'Popup'
export const i19post = 'Post'
export const i19posted = 'Postado'
export const i19postingIn = 'Seu pedido será enviado em até'
export const i19price = 'Preço'
export const i19pricing = 'Precificação'
export const i19printBillet = 'Imprimir boleto'
export const i19privacy = 'Privacidade'
export const i19privacyPolicy = 'Política de privacidade'
export const i19product = 'Produto'
export const i19products = 'Produtos'
export const i19productsPurchased = 'Produtos comprados pelos clientes'
export const i19profileNotFound = 'Nenhum perfil encontrado com o endereço de e-mail'
export const i19province = 'Nome do estado'
export const i19provinceCode = 'UF'
export const i19quantity = 'Quantidade'
export const i19rating = 'Avaliação'
export const i19read = 'Lido'
export const i19receivedOrder = 'Recebemos seu pedido'
export const i19receiveNewsletter = 'Receber newsletter'
export const i19recipient = 'Recipiente'
export const i19redirectToPayment = 'Redirecionamento de pagamento'
export const i19reference = 'Referência'
export const i19referral = 'Cliente convidado por'
export const i19referringSite = 'Site de referência'
export const i19registerToBuy = 'Complete seu cadastro para prosseguir com a compra'
export const i19registration = 'Cadastro'
export const i19relatedSearch = 'Consultas relacionadas'
export const i19relatedProduct = 'Produtos Relacionados'
export const i19remove = 'Remover'
export const i19resultsFor = 'Resultados para'
export const i19retail = 'Retenção'
export const i19reviews = 'Avaliações de Clientes'
export const i19sales = 'Vendas'
export const i19salesChannels = 'Canais de vendas'
export const i19save = 'Salvar'
export const i19saved = 'Salvo'
export const i19search = 'Buscar'
export const i19securityCode = 'Cõdigo de segurança'
export const i19seeAll = 'Ver todos'
export const i19seeAllApps = 'Ver todos aplicativos'
export const i19seeAllThemes = 'Ver todos temas'
export const i19seeCart = 'Ver carrinho'
export const i19seeMoreCategory = 'Veja mais categorias'
export const i19seeMoreInfo = 'Veja mais'
export const i19seeOrder = 'Visualizar pedido'
export const i19sellerRecommendations = 'Recomendações do vendedor'
export const i19sellerRecommendationsProducts = 'Lista de produtos recomendados'
export const i19sellerRecommendationsTitle = 'Título da coleção recomendada'
export const i19seo = 'SEO'
export const i19shareWhats = 'Compartilhar no Whatsapp'
export const i19shipped = 'Enviado'
export const i19shippedBy = 'Enviado por'
export const i19shippingAddress = 'Endereço de entrega'
export const i19shippingMethod = 'Opções de envio'
export const i19shippingMethodLabel = 'Nome da forma de envio'
export const i19shopByCategory = 'Compre por categorias'
export const i19shopByFranchise = 'Compre por marcas'
export const i19shopNow = 'Compre agora'
export const i19shoppingCart = 'Carrinho de compras'
export const i19short = 'Curta'
export const i19shortDescription = 'Descrição curta'
export const i19show = 'Mostrar'
export const i19showDescription = 'Mostrar toda descrição'
export const i19showReview = 'Mostrar toda avaliação'
export const i19signInWith = 'Entrar com'
export const i19signIn = 'Entrar'
export const i19signUpWith = 'Cadastrar via'
export const i19signUp = 'Cadastrar'
export const i19size = 'Tamanho'
export const i19sku = 'Sku'
export const i19slug = 'Slug (URL)'
export const i19socialLogin = 'Login social'
export const i19socialMedia = 'Mídia social'
export const i19source = 'Origem'
export const i19sort = 'Ordenar'
export const i19sortBy = 'Ordenar por'
export const i19staffNotes = 'Observação do admnistrador'
export const i19staffSignature = 'Criado pelo admnistrador'
export const i19star = 'Estrela'
export const i19state = 'Estado'
export const i19status = 'Status'
export const i19street = 'Rua'
export const i19store = 'Loja'
export const i19storefront = 'Storefront'
export const i19subtitle = 'Subtítulo para SEO'
export const i19subtotal = 'Subtotal'
export const i19success = 'Sucesso'
export const i19summary = 'Resumo'
export const i19support = 'Suporte'
export const i19taxExempt = 'Impostos e taxas'
export const i19termSearched = 'Termo pesquisado'
export const i19test = 'Teste'
export const i19thanks = 'Obrigado!'
export const i19thanksForPurchase = 'Agradecemos por sua compra!'
export const i19theme = 'Tema'
export const i19themes = 'Temas'
export const i19ticketCode = 'Código de barras do boleto'
export const i19title = 'Título'
export const i19titleTag = 'Title tag'
export const i19to = 'Por'
export const i19today = 'Hoje'
export const i19token = 'Token'
export const i19total = 'Total'
export const i19totalCancelled = 'Valor total de compras canceladas'
export const i19totalResultsFor = 'Produtos encontrados para'
export const i19totalSpent = 'Valor total de compras confirmadas'
export const i19transactionCode = 'Código da transação'
export const i19trendingApps = 'Aplicativos populares'
export const i19type = 'Tipo'
export const i19unavailable = 'Indisponível'
export const i19uninstall = 'Desinstalar'
export const i19unlimited = 'Ilimitado'
export const i19unsub = 'Cancelar assinatura'
export const i19update = 'Atualização'
export const i19upTo = 'Até'
export const i19username = 'Username'
export const i19utm = 'Utm'
export const i19utmCampaign = 'Nome da campanha'
export const i19utmContent = 'Conteúdo da campanha'
export const i19utmMedium = 'Mídia da campanha'
export const i19utmSource = 'Origem do utm'
export const i19utmTerm = 'Termo da campanha'
export const i19url = 'Url'
export const i19validThru = 'Validade'
export const i19value = 'Valor'
export const i19verified = 'Verificado'
export const i19version = 'Versão'
export const i19versionDate = 'Data da versão'
export const i19visitor = 'Visitante'
export const i19visitorCheckout = 'Você também pode comprar como visitante se preferir'
export const i19warning = 'Aviso'
export const i19wasAnErrorOnLogin = 'Houve um erro ao tentar o login, por favor tente novamente ou selecione outra opção'
export const i19weFrom = 'Nós da'
export const i19welcome = 'Boas vindas'
export const i19welcomeText = 'Ficamos felizes com seu cadastro. Dê uma olhada em nossos produtos e aproveite as ofertas!'
export const i19weUseYourDataTo = 'Usaremos seus dados com segurança e responsabilidade para'
export const i19widgets = 'Widgets'
export const i19willReceiveMsg = 'Você receberá os produtos em até'
export const i19withoutInstallmentRates = 'Sem taxas de parcelamento'
export const i19write = 'Escreva'
export const i19writeReview = 'Escreva uma avaliação'
export const i19workingDays = 'Dias úteis'
export const i19year = 'Ano'
export const i19zipCode = 'CEP'

export const i19DiscountApplyAt = {
  total: 'Total',
  subtotal: 'Subtotal',
  freight: 'Frete'
}

export const i19DiscountType = {
  percentage: 'Percentual',
  fixed: 'Fixo'
}

export const i19InscriptionType = {
  state: 'Estadual',
  municipal: 'Municipal'
}

export const i19FinancialStatus = {
  pending: 'Aguardando pagamento',
  under_analysis: 'Pagamento em análise',
  authorized: 'Pagamento autorizado',
  unauthorized: 'Pagamento não autorizado',
  partially_paid: 'Parcialmente pago',
  paid: 'Pagamento aprovado',
  dispute: 'Pagamento em disputa',
  partially_refunded: 'Pagamento parcialemente devolvido',
  refunded: 'Pagamento devolvido',
  voided: 'Pagamento cancelado',
  unknown: 'Situação do pagamento desconhecida'
}

export const i19FinancialStatusMsg = {
  pending: 'Seu pedido está',
  under_analysis: 'Seu pedido está com',
  authorized: 'Seu pedido está com',
  unauthorized: 'Seu pedido está com',
  partially_paid: 'Seu pedido está',
  paid: 'Seu pedido está com',
  dispute: 'Seu pedido está com',
  partially_refunded: 'Seu pedido está com',
  refunded: 'Seu pedido está com',
  voided: 'Seu pedido está com',
  unknown: 'Seu pedido está com'
}

export const i19FulfillmentStatus = {
  ready_for_shipping: 'Pronto para envio',
  shipped: 'Enviado',
  delivered: 'Entregue',
  invoice_issued: 'NF emitida',
  in_production: 'Em produção',
  in_separation: 'Em separação',
  partially_shipped: 'Parte enviado',
  partially_delivered: 'Parte entregue',
  returned_for_exchange: 'Retorno da troca',
  received_for_exchange: 'Recebido para troca',
  returned: 'Devolvido'
}

export const i19FulfillmentStatusMsg = {
  ready_for_shipping: 'Seu pedido está',
  shipped: 'Seu pedido foi',
  delivered: 'Seu pedido foi',
  invoice_issued: 'Sua',
  in_production: 'Seu pedido está',
  in_separation: 'Seu pedido está',
  partially_shipped: 'Seu pedido foi',
  partially_delivered: 'Seu pedido foi',
  returned_for_exchange: 'Seu pedido tem',
  received_for_exchange: 'Seu pedido foi',
  returned: 'Seu pedido foi'
}

export const i19Modules = {
  page_loaded: 'Página carregada',
  term_searched: 'Termo procurado',
  cart_confirmed: 'Carrinho confirmado',
  calculate_shipping: 'Calcular frete',
  list_payments: 'Listar formas de pagamento',
  apply_discount: 'Aplicar desconto',
  create_transaction: 'Criar transação',
  checkout_done: 'Checkout finalizado'
}

export const i19OrderStatus = {
  open: 'Pedido aberto',
  closed: 'Pedido finalizado',
  cancelled: 'Cancelado'
}

export const i19PhoneType = {
  home: 'Casa',
  personal: 'Pessoal',
  work: 'Trabalho',
  other: 'Outro'
}

export const i19RegistryType = {
  p: 'Pessoa física',
  j: 'Pessoa jurídica'
}

export const i19StateRegister = {
  invited: 'Convidado',
  registered: 'Registrado',
  declined: 'Recusado'
}
