export const AboutCvv = '3 ou 4 dígitos, geralmente no verso do cartão (na frente em cartões AMEX)'
export const AcceptAttachedFile = 'Aceitar arquivo em anexo'
export const AcceptCustomOptionByCustomer = 'Aceitar opção personalizada pelo cliente'
export const Active = 'Ativo'
export const Add = 'Adicionar'
export const Additional = 'Adicional'
export const Addresses = 'Endereços'
export const AddPref = 'Adicionar aos desejos'
export const AddToPrice = 'Adicionar preço'
export const AdminSettings = 'Configurações no painel'
export const Advanced = 'Avançado'
export const AffiliateCoede = 'Código do afiliado'
export const Alt = 'Tag alt'
export const AlterationPrice = 'Alteração padrão de preço nos produtos com essa grade para personalização ou variações.'
export const Another = 'Outro'
export const ApplyDiscount = 'Aplicar desconto'
export const AtSight = 'À vista'
export const Attachment = 'Anexar'
export const Authentication = 'Autenticação'
export const Available = 'Disponível para compra'
export const BackToCart = 'Voltar ao carrinho'
export const Bag = 'Sacola'
export const Banner = 'Banner'
export const Banners = 'Banners'
export const Birthdate = 'Data de nascimento'
export const Borough = 'Bairro'
export const Buy = 'Comprar'
export const Buyer = 'Comprador'
export const By = 'Por'
export const Brand = 'Marca'
export const BrandName = 'Nome da marca'
export const BuyWith = 'Comprar Juntos'
export const CalculateShipping = 'Calcular frete e prazo'
export const Callback = 'Callback'
export const CardNumber = 'Número do cartão'
export const CartConfirmed = 'Carrinho confirmado'
export const CartItems = 'Itens do Carrinho'
export const Category = 'Categoria'
export const CategoryBanners = 'Banner da categoria'
export const CategoryName = 'Nome da categoria'
export const Cellphone = 'Celular'
export const ChangePaymentMethod = 'Alterar forma de pagamento'
export const ChangeShippingMethod = 'Alterar forma de envio'
export const Channel = 'Canal'
export const Channels = 'Canais'
export const Checkout = 'Finalizar compra'
export const CheckoutEnabled = 'Checkout habilitado'
export const CheckoutDone = 'Checkout finalizado'
export const City = 'Cidade'
export const Close = 'Fechar'
export const Code = 'Código'
export const CodeCopied = 'Código copiado'
export const Collection = 'Coleção'
export const Collections = 'Coleções'
export const CollectionBanners = 'Banner da coleção'
export const CollectionItems = 'Itens da coleção'
export const CollectionName = 'Nome da coleção'
export const Color = 'Cor'
export const Colors = 'Cores'
export const CompanyRegistration = 'Pessoa jurídica'
export const CompareProducts = 'Produtos Similares'
export const Complement = 'Complemento'
export const ComplementInformation = 'Informação complementar'
export const ConfirmPurchase = 'Confirmar compra'
export const ContactPhone = 'Telefone de contato'
export const Content = 'Conteúdo'
export const Continue = 'Continuar'
export const ContinueShopping = 'Continuar comprando'
export const Control = 'Controle'
export const CopyCode = 'Copiar código'
export const CopyErrorMsg = 'Erro ao copiar para a área de transferência, por favor copie manualmente'
export const CountryCode = 'Código do país'
export const CreateTransaction = 'Criar a transação'
export const Creation = 'Criação'
export const Custom = 'Personalização'
export const CustomValue = 'Opção personalizada'
export const Customer = 'Cliente'
export const Dashboard = 'Painel'
export const Day = 'Dia'
export const Days = 'Dias'
export const Danger = 'Perigo'
export const Delete = 'Deletar'
export const Delivery = 'Entrega'
export const DeliverTrack = 'Rastreamento de pedido'
export const Description = 'Descrição'
export const DidYouMean = 'Você quis dizer'
export const Discount = 'Desconto'
export const DiscountOf = 'Desconto de'
export const DisplayName = 'Apelido'
export const DocNumber = 'Número do documento'
export const DoPaymentMsg = 'Por favor finalize o pagamento para confirmar sua compra'
export const Edit = 'Editar'
export const EditAdditionalCost = 'Editar custo adicional'
export const EditDispatchAndFulfillment = 'Editar envio e atendimento'
export const EditObservationInfo = 'Editar observação do cliente'
export const Email = 'E-mail'
export const EmailAddress = 'Endereço de e-mail'
export const EmptyCart = 'Seu carrinho de compras está vazio'
export const Enabled = 'Habilitado'
export const Endpoint = 'Endpoint'
export const EnterYourDocNumber = 'Confirme o login com seu documento'
export const EnterYourEmail = 'Informe seu email para prosseguir'
export const Events = 'Eventos'
export const External = 'Externo'
export const FamilyName = 'Último nome'
export const Female = 'Feminino'
export const Field = 'Campo'
export const Free = 'Grátis'
export const FreeShipping = 'Frete grátis'
export const Freight = 'Frete'
export const From = 'De'
export const FullName = 'Full name'
export const Gender = 'Gênero'
export const GenderX = 'Outros'
export const GenerateBillet = 'Gerar boleto'
export const GiftListOwnerID = 'Especificar ID do cliente que receberá presente'
export const GiftOption = 'Adicionar na lista de presentes'
export const GitRepository = 'Repositório do github'
export const GivenName = 'Primeiro nome'
export const GoogleProductCategoryId = 'ID da categoria no Google'
export const GridId = 'ID do grid'
export const Grids = 'Grids'
export const GridName = 'Nome da grade'
export const Hello = 'Olá'
export const HelloAgain = 'Olá novamente'
export const HolderName = 'Nome do titular'
export const Home = 'Home'
export const Icon = 'Ícone'
export const Id = 'ID'
export const Identification = 'Identificação'
export const IdentifyAccount = 'Identifique-se ou crie sua conta'
export const Inactive = 'Inativo'
export const Info = 'Informação'
export const InvalidCard = 'Cartão inválido'
export const InvalidCardMsg = 'Não foi possível validar este cartão, por favor verifique os dados ou tente novamente mais tarde'
export const InvalidLoginInfo = 'Login inválido, por favor verifique os dados informados'
export const InterestFree = 'Sem juros'
export const InStock = 'Disponível'
export const InStockAt = 'Busque em'
export const IsFilter = 'Resultados do filtro'
export const IsNotYou = 'Não é você'
export const Items = 'Itens'
export const Last = 'Último'
export const LastOptions = 'Últimas unidades disponíveis'
export const List = 'Listar'
export const ListPayments = 'Listar formas de pagamento'
export const Load = 'Carregar'
export const Locale = 'Idioma do cliente (pt_br)'
export const Login = 'Login'
export const LoginEnabled = 'Login habilitado'
export const LoginError = 'Houve um erro ao tentar o login, por favor tente novamente ou tente outra opção'
export const Logo = 'Logo'
export const Logout = 'Sair'
export const MainEmail = 'E-mail principal'
export const Male = 'Masculino'
export const ManageYourHistory = 'Gerenciar seu histórico de compras'
export const MetaTagDescription = 'Meta description tag'
export const MiddleName = 'Sobrenome do meio'
export const MlCategoryId = 'ID da categoria no ML'
export const MobileLink = 'Links específicos para celular'
export const Modules = 'Módulos'
export const Month = 'Mês'
export const MostPop = 'Mais populares'
export const MyAccount = 'Minha conta'
export const MyCart = 'Meu carrinho'
export const MyOrders = 'Meus pedidos'
export const Name = 'Nome'
export const NameOnCard = 'Nome impresso cartão'
export const New = 'Novo'
export const Nickname = 'Apelido'
export const NewAddress = 'Novo endereço'
export const NoAdditional = 'Sem adicional'
export const NoResultsFor = 'Nenhum produto encontrado para'
export const Normal = 'Normal'
export const Notifications = 'Notificações'
export const NotifyAboutOrders = 'Notificar sobre o andamento do pedido'
export const Notes = 'Informação adicional'
export const NoNumber = 'S/N'
export const Number = 'Número'
export const OauthOnPopup = 'Continue o login no pop-up'
export const Of = 'De'
export const OfDiscount = 'Desconto de'
export const OnFreight = 'Frete de'
export const Options = 'Options'
export const Orders = 'Pedido'
export const OrderCreated = 'Pedido criado'
export const OrderConfirmationMsg = 'Seu pedido foi confirmado, obrigado pela preferência'
export const OrderNumber = 'Número do pedido'
export const OrProceedWith = 'Ou prossiga com'
export const OtherCustomers = 'Disponível para outros clientes'
export const OutOfStock = 'Sem estoque'
export const PageLoaded = 'Página carregada'
export const Paid = 'Pago'
export const ParcelIn = 'Parcelar em'
export const ParentCategory = 'Categoria pai'
export const Payment = 'Pagamento'
export const PaymentConfirmed = 'Pagamento confirmado'
export const PaymentRealized = 'Pagamento realizado'
export const PaymentError = 'Erro no pagamento'
export const PaymentErrorMsg = 'Não foi possível aprovar a compra, por favor verifique os dados ou tente com outra forma de pagamento'
export const PersonalRegistration = 'Pessoa física'
export const Permalink = 'Link permanente'
export const Phone = 'Telefone'
export const Phones = 'Telefones'
export const Photo = 'Foto'
export const Photos = 'Fotos'
export const Pickup = 'Coleta'
export const Picture = 'Imagem'
export const Pictures = 'Imagens'
export const Price = 'Preço'
export const PrintBillet = 'Imprimir boleto'
export const Product = 'Produto'
export const Products = 'Produtos'
export const ProfileNotFound = 'Nenhum perfil encontrado com o endereço de e-mail'
export const ProvinceCode = 'UF'
export const Quantity = 'Quantidade'
export const Read = 'Lido'
export const ReceiveNewsletter = 'Receber newsletter'
export const Recipient = 'Recipiente'
export const RedirectToPayment = 'Redirecionamento de pagamento'
export const Reference = 'Referência'
export const Referral = 'Cliente convidado por'
export const ReferringSite = 'Site de referência'
export const RegisterToBuy = 'Complete seu cadastro para prosseguir com a compra'
export const Registration = 'Cadastro'
export const RelatedSearch = 'Consultas relacionadas'
export const RelatedProduct = 'Produtos Relacionados'
export const Remove = 'Remover'
export const ResultsFor = 'Resultados para'
export const Reviews = 'Avaliações de Clientes'
export const Save = 'Salvar'
export const SecurityCode = 'Cõdigo de segurança'
export const SeeAll = 'Ver todos'
export const SeeCart = 'Ver carrinho'
export const SeeMoreCategory = 'Veja mais categorias'
export const SeeMoreInfo = 'Veja mais'
export const ShareWhats = 'Compartilhar no Whatsapp'
export const Shipped = 'Enviado'
export const ShippingMethod = 'Opções de envio'
export const ShopByCategory = 'Compre por categorias'
export const ShopByFranchise = 'Compre por marcas'
export const ShopNow = 'Compre agora'
export const ShoppingCart = 'Carrinho de compras'
export const Short = 'Curta'
export const ShortDescription = 'Descrição curta'
export const SignInWith = 'Entrar com'
export const SignIn = 'Entrar'
export const SignUpWith = 'Cadastrar via'
export const SignUp = 'Cadastrar'
export const Size = 'Tamanho'
export const Sku = 'Sku'
export const Slug = 'Slug (URL)'
export const Source = 'Origem'
export const StaffSignature = 'Criado pelo admnistrador'
export const State = 'Estado'
export const Status = 'Status'
export const Street = 'Rua'
export const Storefront = 'Storefront'
export const Subtitle = 'Subtítulo para SEO'
export const Subtotal = 'Subtotal'
export const Success = 'Sucesso'
export const Summary = 'Resumo'
export const TermSearched = 'Termo pesquisado'
export const Test = 'Teste'
export const TicketCode = 'Código de barras do boleto'
export const Title = 'Título'
export const TitleTag = 'Title tag'
export const To = 'Por'
export const Today = 'Hoje'
export const Total = 'Total'
export const TotalResultsFor = 'Produtos encontrados para'
export const Type = 'Tipo'
export const Unavailable = 'Indisponível'
export const Update = 'Atualização'
export const UpTo = 'Até'
export const Username = 'Username'
export const Utm = 'Utm'
export const UtmCampaign = 'Nome da campanha'
export const UtmContent = 'Conteúdo da campanha'
export const UtmMedium = 'Mídia da campanha'
export const UtmSource = 'Origem do utm'
export const UtmTerm = 'Termo da campanha'
export const Url = 'Url'
export const ValidThru = 'Validade'
export const Value = 'Valor'
export const Version = 'Versão'
export const VersionDate = 'Data da versão'
export const Visitor = 'Visitante'
export const VisitorCheckout = 'Você também pode comprar como visitante se preferir'
export const Warning = 'Aviso'
export const WasAnErrorOnLogin = 'Houve um erro ao tentar o login, por favor tente novamente ou selecione outra opção'
export const WeUseYourDataTo = 'Usaremos seus dados com segurança e responsabilidade para'
export const WillReceiveMsg = 'Você receberá os produtos em até'
export const WorkingDays = 'Dias úteis'
export const Year = 'Ano'
export const ZipCode = 'CEP'

export const _FinancialStatus = {
  pending: 'Aguardando pagamento',
  under_analysis: 'Pagamento em análise',
  authorized: 'Pagamento autorizado',
  unauthorized: 'Pagamento não autorizado',
  partially_paid: 'Parcialmente pago',
  paid: 'Pago',
  dispute: 'Pagamento em disputa',
  partially_refunded: 'Pagamento parcialemente devolvido',
  refunded: 'Pagamento devolvido',
  voided: 'Pagamento cancelado',
  unknown: 'Situação do pagamento desconhecida'
}
export const _OrderStatus = {
  open: 'Pedido aberto',
  closed: 'Pedido finalizado',
  cancelled: 'Cancelado'
}
export const _FulfillmentStatus = {
  ready_for_shipping: 'Pronto para envio',
  shipped: 'Enviado',
  delivered: 'Entregue'
}
export const _modules = {
  pageLoaded: 'Pãgina carregada',
  termSearched: 'Termo procurado',
  cartConfirmed: 'Carrinho confirmado',
  calculateShipping: 'Calcular frete',
  listPayments: 'Listar formas de pagamento',
  applyDiscount: 'Aplicar desconto',
  createTransaction: 'Criar transação',
  checkoutDone: 'Checkout finalizado'
}
export const _discountApplyAt = {
  total: 'Total',
  subtotal: 'Subtotal',
  freight: 'Frete'
}
export const _discountType = {
  percentage: 'Percentual',
  fixed: 'Fixo'
}
export const _stateRegister = {
  invited: 'Convidado',
  registered: 'Registrado',
  declined: 'Recusado'
}
export const _phoneType = {
  home: 'Casa',
  personal: 'Pessoal',
  work: 'Trabalho',
  other: 'Outro'
}
export const _registryType = {
  p: 'Pessoa física',
  j: 'Pessoa jurídica'
}