export const About = 'Sobre nós'
export const AboutCvv = '3 ou 4 dígitos, geralmente no verso do cartão (na frente em cartões AMEX)'
export const AcceptAttachedFile = 'Aceitar arquivo em anexo'
export const AcceptCustomOptionByCustomer = 'Aceitar opção personalizada pelo cliente'
export const Active = 'Ativo'
export const Add = 'Adicionar'
export const AddApp = 'Adicionar aplicativo'
export const AddCart = 'Adicionar ao carrinho'
export const AddClient = 'Adicionar Cliente'
export const Additional = 'Adicional'
export const AdditionalCost = 'Custo adicional'
export const Address = 'Endereço'
export const Addresses = 'Endereços'
export const AddressesName = 'Destinatário'
export const AddPref = 'Adicionar aos desejos'
export const AddToPrice = 'Adicionar preço'
export const AdminSettings = 'Configurações no painel'
export const Advanced = 'Avançado'
export const AffiliateCoede = 'Código do afiliado'
export const AfterPayment = 'Após a confirmação do pagamento'
export const Alt = 'Tag alt'
export const AlterationPrice = 'Alteração padrão de preço nos produtos com essa grade para personalização ou variações.'
export const Another = 'Outro'
export const App = 'Aplicativo'
export const AppDevelopers = 'Desenvolvedor de aplicativos'
export const ApplyDiscount = 'Aplicar desconto'
export const AtSight = 'À vista'
export const Attachment = 'Anexar'
export const Authentication = 'Autenticação'
export const Available = 'Disponível para compra'
export const BackToCart = 'Voltar ao carrinho'
export const Bag = 'Sacola'
export const Banner = 'Banner'
export const Banners = 'Banners'
export const Birthdate = 'Data de nascimento'
export const BillingAddress = 'Endereço de cobrança'
export const Borough = 'Bairro'
export const Buy = 'Comprar'
export const Buyer = 'Comprador'
export const By = 'Por'
export const Brand = 'Marca'
export const BrandName = 'Nome da marca'
export const Brazil = 'Brasil'
export const BuyWith = 'Comprar Juntos'
export const CalculateShipping = 'Calcular frete e prazo'
export const Callback = 'Callback'
export const Cancel = 'Cancelar'
export const Cancelled = 'Cancelado'
export const CardNumber = 'Número do cartão'
export const CartConfirmed = 'Carrinho confirmado'
export const CartDetails = 'Detalhes do carrinho'
export const CartItems = 'Itens do Carrinho'
export const Category = 'Categoria'
export const CategoryBanners = 'Banner da categoria'
export const CategoryName = 'Nome da categoria'
export const Cellphone = 'Celular'
export const ChangePaymentMethod = 'Alterar forma de pagamento'
export const ChangeShippingMethod = 'Alterar forma de envio'
export const Channel = 'Canal'
export const Channels = 'Canais'
export const Checkout = 'Finalizar compra'
export const CheckoutEnabled = 'Checkout habilitado'
export const CheckoutDone = 'Checkout finalizado'
export const City = 'Cidade'
export const Close = 'Fechar'
export const Code = 'Código'
export const CodeCopied = 'Código copiado'
export const Collection = 'Coleção'
export const Collections = 'Coleções'
export const CollectionBanners = 'Banner da coleção'
export const CollectionItems = 'Itens da coleção'
export const CollectionName = 'Nome da coleção'
export const Color = 'Cor'
export const Colors = 'Cores'
export const Community = 'Comunidade'
export const CompanyRegistration = 'Pessoa jurídica'
export const CompareProducts = 'Produtos Similares'
export const Complement = 'Complemento'
export const ComplementInformation = 'Informação complementar'
export const ConfirmPurchase = 'Confirmar compra'
export const ContactPhone = 'Telefone de contato'
export const ContactUs = 'Se houver alguma dúvida entre em contato conosco.'
export const Content = 'Conteúdo'
export const Continue = 'Continuar'
export const ContinueShopping = 'Continuar comprando'
export const Control = 'Controle'
export const CopyCode = 'Copiar código'
export const CopyErrorMsg = 'Erro ao copiar para a área de transferência, por favor copie manualmente'
export const CorporateName = 'Razão sozial da empresa'
export const CountryCode = 'Código do país'
export const CreateTransaction = 'Criar a transação'
export const Creation = 'Criação'
export const Credit = 'Crédito'
export const CreditCard = 'Cartão de credito'
export const CreditCardBin = 'Número de indetificação do cartão'
export const CreditCardCompany = 'Emissora do cartao'
export const CreditCardHolderName = 'Nome no cartão'
export const CreditCardLastDigits = 'Últimos dígitos do cartão'
export const CurrencyId = 'Identificador da moeda'
export const CurrencySymbol = 'Símbolo monetário'
export const Custom = 'Personalização'
export const CustomValue = 'Opção personalizada'
export const Customer = 'Cliente'
export const Dashboard = 'Painel'
export const Day = 'Dia'
export const Days = 'Dias'
export const Danger = 'Perigo'
export const Delete = 'Deletar'
export const Delivery = 'Entrega'
export const DeliveryIn = 'Seu pedido será entregue em até'
export const DeliverTrack = 'Rastreamento de pedido'
export const Description = 'Descrição'
export const Desktop = 'Desktop'
export const Details = 'Detalhes'
export const DidYouMean = 'Você quis dizer'
export const DirectLinkPayment = 'Link para pagamento'
export const Discount = 'Desconto'
export const DiscountOf = 'Desconto de'
export const DiscountValue = 'Desconto fixo, percentual ou por valor'
export const DisplayName = 'Apelido'
export const DocCountry = 'País de emissão do documento'
export const DocNumber = 'Número do documento'
export const Docs = 'Documentação'
export const DoPaymentMsg = 'Por favor finalize o pagamento para confirmar sua compra'
export const Edit = 'Editar'
export const EditAdditionalCost = 'Editar custo adicional'
export const EditComments = 'Editar configuração'
export const EditDispatchAndFulfillment = 'Editar envio e atendimento'
export const EditObservationInfo = 'Editar observação do cliente'
export const EditPaymentDetails = 'Editar detalhes do pagamento'
export const Email = 'E-mail'
export const EmailAddress = 'Endereço de e-mail'
export const EmailCartText = 'Você pode concluí-la agora, enquanto o carrinho ainda está disponível. Não perca essa chance!'
export const EmailCartTitle = 'Você não finalizou sua compra!'
export const EmailDeliveredText = 'Esperamos que tenha gostado da experiência de compra e em breve visite novamente nosso site. O pedido foi entregue no endereço abaixo'
export const EmailDeliveredTitle = 'Sua compra foi entregue!'
export const EmailInfo = 'Qualquer atualização no pedido será notificada por e-mail, você também pode acompanhar o andamento pela página'
export const EmailMarketing = 'E-mail marketing'
export const EmailShippedText = 'Seu pacote já foi entregue para a transportadora. Para acompanhar o andamento da entrega acesse a página'
export const EmailShippedTitle = 'Seu pedido está a caminho!'
export const EmptyCart = 'Seu carrinho de compras está vazio'
export const Enabled = 'Habilitado'
export const Endpoint = 'Endpoint'
export const EnterYourDocNumber = 'Confirme o login com seu documento'
export const EnterYourEmail = 'Informe seu email para prosseguir'
export const Erp = 'ERP'
export const Events = 'Eventos'
export const Extra = 'Extra'
export const External = 'Externo'
export const FamilyName = 'Último nome'
export const FeaturedApps = 'Aplicativos em destaque'
export const Female = 'Feminino'
export const Field = 'Campo'
export const FinancialStatus = 'Status financeiro'
export const FollowingAddress = 'Para o endereço abaixo'
export const Free = 'Grátis'
export const FreeShipping = 'Frete grátis'
export const Freight = 'Frete'
export const From = 'De'
export const FulfillmentStatus = 'Status de entrega'
export const FullName = 'Full name'
export const Gateway = 'Gateway'
export const Gender = 'Gênero'
export const GenderX = 'Outros'
export const GenerateBillet = 'Gerar boleto'
export const GiftList = 'Adicionar na lista de presentes'
export const GiftsListInfo = 'Informações da lista de presente'
export const GiftsListInfoAuthors = 'Criadores da lista de presente'
export const GiftsListInfoContact = 'Contato do criador da lista de presente'
export const GiftsListInfoDescription = 'Descrição da lista de presente'
export const GiftsListInfoEventDate = 'Data do evento'
export const GiftsListInfoNotification = 'E-mail de produtos comprados da lista de presente'
export const GiftsListInfoPermalink = 'Link permanente da lista'
export const GiftsListInfoTitle = 'Título da lista de presente'
export const GiftsListInfoValidThru = 'Validade da lista de presente'
export const GiftListOwnerID = 'Especificar ID do cliente que receberá presente'
export const GiftListWaiting = 'Lista de presente'
export const GitRepository = 'Repositório do github'
export const GivenName = 'Primeiro nome'
export const GoToStore = 'Ir para a loja'
export const GoogleProductCategoryId = 'ID da categoria no Google'
export const GridId = 'ID do grid'
export const Grids = 'Grids'
export const GridName = 'Nome da grade'
export const Hello = 'Olá'
export const HelloAgain = 'Olá novamente'
export const Help = 'Ajuda'
export const Helpful = 'Útil'
export const High = 'Alto'
export const HighPriority = 'Prioridade máxima'
export const HolderName = 'Nome do titular'
export const Home = 'Home'
export const Icon = 'Ícone'
export const Id = 'ID'
export const Identification = 'Identificação'
export const IdentifyAccount = 'Identifique-se ou crie sua conta'
export const In = 'Em'
export const Inactive = 'Inativo'
export const Info = 'Informação'
export const InscriptionNumber = 'Número da inscrição estadual/municipal'
export const Install = 'Instalar'
export const InstallNow = 'Instalar agora'
export const InStock = 'Disponível'
export const InStockAt = 'Busque em'
export const InterestFree = 'Sem juros'
export const Intermediator = 'Intermediador'
export const InvalidCard = 'Cartão inválido'
export const InvalidCardMsg = 'Não foi possível validar este cartão, por favor verifique os dados ou tente novamente mais tarde'
export const InvalidLoginInfo = 'Login inválido, por favor verifique os dados informados'
export const IsFilter = 'Resultados do filtro'
export const IsNotYou = 'Não é você'
export const Item = 'Item'
export const Items = 'Itens'
export const Keywords = 'Palavras chave'
export const Last = 'Último'
export const LastOptions = 'Últimas unidades disponíveis'
export const LastSearchedTerms = 'Últimos produtos visitados'
export const LastVisitedProducts = 'Últimos produtos visitados pelo cliente'
export const Launch = 'Lançamento'
export const Launching = 'Lançando'
export const LineAddress = 'Endereço completo'
export const List = 'Listar'
export const ListPayments = 'Listar formas de pagamento'
export const Load = 'Carregar'
export const Locale = 'Idioma do cliente (pt_br)'
export const Login = 'Login'
export const LoginEnabled = 'Login habilitado'
export const LoginError = 'Houve um erro ao tentar o login, por favor tente novamente ou tente outra opção'
export const Logo = 'Logo'
export const Logout = 'Sair'
export const LoyaltyPoints = 'Pontos do programa de fidalidade'
export const MadeBy = 'Feito por'
export const MainEmail = 'E-mail principal'
export const Male = 'Masculino'
export const ManageYourHistory = 'Gerenciar seu histórico de compras'
export const Marketing = 'Marketing'
export const Media = 'Mídia'
export const MediaGallery = 'Galeria de imagens'
export const MetaTagDescription = 'Meta description tag'
export const Marketplace = 'Marketplace'
export const Marketplaces = 'Marketplaces'
export const MiddleName = 'Sobrenome do meio'
export const MlCategoryId = 'ID da categoria no ML'
export const Mobile = 'Mobile'
export const MobileLink = 'Links específicos para celular'
export const Modules = 'Módulos'
export const Month = 'Mês'
export const MostPop = 'Mais populares'
export const MyAccount = 'Minha conta'
export const MyCart = 'Meu carrinho'
export const MyOrders = 'Meus pedidos'
export const Name = 'Nome'
export const NameOnCard = 'Nome impresso cartão'
export const NearTo = 'Referência do endereço'
export const New = 'Novo'
export const Next = 'Próximo'
export const Nickname = 'Apelido'
export const NewAddress = 'Novo endereço'
export const NoAdditional = 'Sem adicional'
export const NoResultsFor = 'Nenhum produto encontrado para'
export const Normal = 'Normal'
export const Notifications = 'Notificações'
export const NotifyAboutOrders = 'Notificar sobre o andamento do pedido'
export const Notes = 'Informação adicional'
export const NoNumber = 'S/N'
export const Number = 'Número'
export const OauthOnPopup = 'Continue o login no pop-up'
export const Of = 'De'
export const OfDiscount = 'Desconto de'
export const OnFreight = 'Frete de'
export const OnFollowingAddress = 'No endereço abaixo'
export const Option = 'Opção'
export const Options = 'Opções'
export const Order = 'Pedido'
export const OrderDetails = 'Detalhes do pedido'
export const Orders = 'Pedidos'
export const OrderCreated = 'Pedido criado'
export const OrderConfirmationMsg = 'Seu pedido foi confirmado, obrigado pela preferência'
export const OrdersCount = 'Total de pedidos'
export const OrderItems = 'Itens do pedido'
export const OrderNumber = 'Número do pedido'
export const OrderStatus = 'Status do pedido'
export const OrderValue = 'Valor do pedido'
export const OrdersTotalValue = 'Valor total de pedidos completados'
export const OrProceedWith = 'Ou prossiga com'
export const OtherCustomers = 'Disponível para outros clientes'
export const OutOfStock = 'Sem estoque'
export const PageLoaded = 'Página carregada'
export const Paid = 'Pago'
export const PaidText = 'Recebemos seu pagamento e estamos trabalhando para que você receba seu(s) produto(s) o mais rápido possível'
export const ParcelIn = 'Parcelar em'
export const ParentCategory = 'Categoria pai'
export const Partner = 'Parceiro'
export const Partners = 'Parceiros'
export const PartnersProgram = 'Programa de parceiros'
export const Payment = 'Pagamento'
export const PaymentConfirmed = 'Pagamento confirmado'
export const PaymentDetails = 'Detalhes do pagamento'
export const PaymentError = 'Erro no pagamento'
export const PaymentErrorMsg = 'Não foi possível aprovar a compra, por favor verifique os dados ou tente com outra forma de pagamento'
export const PaymentLink = 'Link de pagamento'
export const PaymentMethod = 'Forma de pagamento'
export const PaymentMethodLabel = 'Nome da forma de pagamento'
export const PaymentRealized = 'Pagamento realizado'
export const PersonalRegistration = 'Pessoa física'
export const Permalink = 'Link permanente'
export const Phone = 'Telefone'
export const Phones = 'Telefones'
export const Photo = 'Foto'
export const Photos = 'Fotos'
export const Pickup = 'Coleta'
export const Picture = 'Imagem'
export const Pictures = 'Imagens'
export const Popup = 'Popup'
export const Post = 'Post'
export const Posted = 'Postado'
export const PostingIn = 'Seu pedido será enviado em até'
export const Price = 'Preço'
export const Pricing = 'Precificação'
export const PrintBillet = 'Imprimir boleto'
export const Privacy = 'Privacidade'
export const PrivacyPolicy = 'Política de privacidade'
export const Product = 'Produto'
export const Products = 'Produtos'
export const ProductsPurchased = 'Produtos comprados pelos clientes'
export const ProfileNotFound = 'Nenhum perfil encontrado com o endereço de e-mail'
export const Province = 'Nome do estado'
export const ProvinceCode = 'UF'
export const Quantity = 'Quantidade'
export const Rating = 'Avaliação'
export const Read = 'Lido'
export const ReceivedOrder = 'Recebemos seu pedido'
export const ReceiveNewsletter = 'Receber newsletter'
export const Recipient = 'Recipiente'
export const RedirectToPayment = 'Redirecionamento de pagamento'
export const Reference = 'Referência'
export const Referral = 'Cliente convidado por'
export const ReferringSite = 'Site de referência'
export const RegisterToBuy = 'Complete seu cadastro para prosseguir com a compra'
export const Registration = 'Cadastro'
export const RelatedSearch = 'Consultas relacionadas'
export const RelatedProduct = 'Produtos Relacionados'
export const Remove = 'Remover'
export const ResultsFor = 'Resultados para'
export const Retail = 'Retenção'
export const Reviews = 'Avaliações de Clientes'
export const Sales = 'Vendas'
export const SalesChannels = 'Canais de vendas'
export const Save = 'Salvar'
export const Saved = 'Salvo'
export const Search = 'Buscar'
export const SecurityCode = 'Cõdigo de segurança'
export const SeeAll = 'Ver todos'
export const SeeAllApps = 'Ver todos aplicativos'
export const SeeAllThemes = 'Ver todos temas'
export const SeeCart = 'Ver carrinho'
export const SeeMoreCategory = 'Veja mais categorias'
export const SeeMoreInfo = 'Veja mais'
export const SeeOrder = 'Visualizar pedido'
export const SellerRecommendations = 'Recomendações do vendedor'
export const SellerRecommendationsProducts = 'Lista de produtos recomendados'
export const SellerRecommendationsTitle = 'Título da coleção recomendada'
export const Seo = 'SEO'
export const ShareWhats = 'Compartilhar no Whatsapp'
export const Shipped = 'Enviado'
export const ShippedBy = 'Enviado por'
export const ShippingAddress = 'Endereço de entrega'
export const ShippingMethod = 'Opções de envio'
export const ShippingMethodLabel = 'Nome da forma de envio'
export const ShopByCategory = 'Compre por categorias'
export const ShopByFranchise = 'Compre por marcas'
export const ShopNow = 'Compre agora'
export const ShoppingCart = 'Carrinho de compras'
export const Short = 'Curta'
export const ShortDescription = 'Descrição curta'
export const Show = 'Mostrar'
export const ShowDescription = 'Mostrar toda descrição'
export const ShowReview = 'Mostrar toda avaliação'
export const SignInWith = 'Entrar com'
export const SignIn = 'Entrar'
export const SignUpWith = 'Cadastrar via'
export const SignUp = 'Cadastrar'
export const Size = 'Tamanho'
export const Sku = 'Sku'
export const Slug = 'Slug (URL)'
export const SocialLogin = 'Login social'
export const SocialMedia = 'Mídia social'
export const Source = 'Origem'
export const Sort = 'Ordenar'
export const SortBy = 'Ordenar por'
export const StaffNotes = 'Observação do admnistrador'
export const StaffSignature = 'Criado pelo admnistrador'
export const Star = 'Estrela'
export const State = 'Estado'
export const Status = 'Status'
export const Street = 'Rua'
export const Store = 'Loja'
export const Storefront = 'Storefront'
export const Subtitle = 'Subtítulo para SEO'
export const Subtotal = 'Subtotal'
export const Success = 'Sucesso'
export const Summary = 'Resumo'
export const Support = 'Suporte'
export const TaxExempt = 'Impostos e taxas'
export const TermSearched = 'Termo pesquisado'
export const Test = 'Teste'
export const Thanks = 'Obrigado!'
export const ThanksForPurchase = 'Agradecemos por sua compra!'
export const Theme = 'Tema'
export const Themes = 'Temas'
export const TicketCode = 'Código de barras do boleto'
export const Title = 'Título'
export const TitleTag = 'Title tag'
export const To = 'Por'
export const Today = 'Hoje'
export const Token = 'Token'
export const Total = 'Total'
export const TotalCancelled = 'Valor total de compras canceladas'
export const TotalResultsFor = 'Produtos encontrados para'
export const TotalSpent = 'Valor total de compras confirmadas'
export const TransactionCode = 'Código da transação'
export const TrendingApps = 'Aplicativos populares'
export const Type = 'Tipo'
export const Unavailable = 'Indisponível'
export const Uninstall = 'Desinstalar'
export const Unlimited = 'Ilimitado'
export const Unsub = 'Cancelar assinatura'
export const Update = 'Atualização'
export const UpTo = 'Até'
export const Username = 'Username'
export const Utm = 'Utm'
export const UtmCampaign = 'Nome da campanha'
export const UtmContent = 'Conteúdo da campanha'
export const UtmMedium = 'Mídia da campanha'
export const UtmSource = 'Origem do utm'
export const UtmTerm = 'Termo da campanha'
export const Url = 'Url'
export const ValidThru = 'Validade'
export const Value = 'Valor'
export const Verified = 'Verificado'
export const Version = 'Versão'
export const VersionDate = 'Data da versão'
export const Visitor = 'Visitante'
export const VisitorCheckout = 'Você também pode comprar como visitante se preferir'
export const Warning = 'Aviso'
export const WasAnErrorOnLogin = 'Houve um erro ao tentar o login, por favor tente novamente ou selecione outra opção'
export const WeFrom = 'Nós da'
export const Welcome = 'Boas vindas'
export const WelcomeText = 'Ficamos felizes com seu cadastro. Dê uma olhada em nossos produtos e aproveite as ofertas!'
export const WeUseYourDataTo = 'Usaremos seus dados com segurança e responsabilidade para'
export const Widgets = 'Widgets'
export const WillReceiveMsg = 'Você receberá os produtos em até'
export const WithoutInstallmentRates = 'Sem taxas de parcelamento'
export const Write = 'Escreva'
export const WriteReview = 'Escreva uma avaliação'
export const WorkingDays = 'Dias úteis'
export const Year = 'Ano'
export const ZipCode = 'CEP'

export const _FinancialStatus = {
  pending: 'Aguardando pagamento',
  under_analysis: 'Pagamento em análise',
  authorized: 'Pagamento autorizado',
  unauthorized: 'Pagamento não autorizado',
  partially_paid: 'Parcialmente pago',
  paid: 'Pagamento aprovado',
  dispute: 'Pagamento em disputa',
  partially_refunded: 'Pagamento parcialemente devolvido',
  refunded: 'Pagamento devolvido',
  voided: 'Pagamento cancelado',
  unknown: 'Situação do pagamento desconhecida'
}
export const _FinancialStatusMsg = {
  pending: 'Seu pedido está',
  under_analysis: 'Seu pedido está com',
  authorized: 'Seu pedido está com',
  unauthorized: 'Seu pedido está com',
  partially_paid: 'Seu pedido está',
  paid: 'Seu pedido está com',
  dispute: 'Seu pedido está com',
  partially_refunded: 'Seu pedido está com',
  refunded: 'Seu pedido está com',
  voided: 'Seu pedido está com',
  unknown: 'Seu pedido está com'
}
export const _OrderStatus = {
  open: 'Pedido aberto',
  closed: 'Pedido finalizado',
  cancelled: 'Cancelado'
}
export const _FulfillmentStatus = {
  ready_for_shipping: 'Pronto para envio',
  shipped: 'Enviado',
  delivered: 'Entregue',
  invoice_issued: 'NF emitida',
  in_production: 'Em produção',
  in_separation: 'Em separação',
  partially_shipped: 'Parte enviado',
  partially_delivered: 'Parte entregue',
  returned_for_exchange: 'Retorno da troca',
  received_for_exchange: 'Recebido para troca',
  returned: 'Devolvido'
}
export const _FulfillmentStatusMsg = {
  ready_for_shipping: 'Seu pedido está',
  shipped: 'Seu pedido foi',
  delivered: 'Seu pedido foi',
  invoice_issued: 'Sua',
  in_production: 'Seu pedido está',
  in_separation: 'Seu pedido está',
  partially_shipped: 'Seu pedido foi',
  partially_delivered: 'Seu pedido foi',
  returned_for_exchange: 'Seu pedido tem',
  received_for_exchange: 'Seu pedido foi',
  returned: 'Seu pedido foi'
}
export const _modules = {
  pageLoaded: 'Página carregada',
  termSearched: 'Termo procurado',
  cartConfirmed: 'Carrinho confirmado',
  calculateShipping: 'Calcular frete',
  listPayments: 'Listar formas de pagamento',
  applyDiscount: 'Aplicar desconto',
  createTransaction: 'Criar transação',
  checkoutDone: 'Checkout finalizado'
}
export const _discountApplyAt = {
  total: 'Total',
  subtotal: 'Subtotal',
  freight: 'Frete'
}
export const _discountType = {
  percentage: 'Percentual',
  fixed: 'Fixo'
}
export const _stateRegister = {
  invited: 'Convidado',
  registered: 'Registrado',
  declined: 'Recusado'
}
export const _phoneType = {
  home: 'Casa',
  personal: 'Pessoal',
  work: 'Trabalho',
  other: 'Outro'
}
export const _registryType = {
  p: 'Pessoa física',
  j: 'Pessoa jurídica'
}
export const _inscriptionType = {
  state: 'Estadual',
  municipal: 'Municipal'
}
